export const LOGIN_SUCCESS = 'ADD_TICKET_SUCCESS'

export const REPLY_SUCCESS = 'REPLY_SUCCESS'

export const REGISTER_SUCCESS='REGISTER_SUCCESS'

export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS";
export const ADD_CAR_FAILED = "ADD_CAR_FAILED";
export const ADD_CAR_EN_LAOD = "";
export const ADD_CAR_DIS_LOAD = "";

export const GET_RESERVATION = "GET_RESERVATION";
export const POST_RESERVATION = "POST_RESERVATION";
export const GET_ALL_RESERVATION = "GET_ALL_RESERVATION";